fail_fast: true

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-added-large-files
    args: ['--maxkb=1024']
  - id: forbid-new-submodules
  - id: detect-private-key

- repo: https://github.com/kynan/nbstripout
  rev: 0.8.1
  hooks:
  - id: nbstripout

- repo: https://github.com/psf/black
  rev: 25.1.0
  hooks:
  - id: black
    args: [
      "--line-length", "120", "src"
    ]
    always_run: true
    verbose: true

- repo: https://github.com/pycqa/isort
  rev: 6.0.1
  hooks:
  - id: isort
    args: [
      "--profile", "black",
      "--line-length", "120",
      "--lines-after-imports", "2",
      "src"
    ]
    always_run: true
    verbose: true

- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.7.14
  hooks:
  - id: uv-lock
    files: ^src/pyproject\.toml$
    args: [
      "--project", "src",
    ]
  - id: uv-export
    files: ^src/pyproject\.toml$
    args: [
      "--project", "src",
      "--no-hashes",
      "--format", "requirements-txt",
      "--output-file", "src/requirements.txt"
    ]
